name: enviar_hora

on:
  push:
    branches: [ main ]

jobs:
  build: 
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v5
    
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13' 
      - name: Run script
        run: python enviar_hora.py

      - name: Commit and Push del log
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Actualiza el log automaticamente
          commit_user_name: Tobba [Github Actions]
          commit_user_email: tooba@gmx.us
          commit_author: tooba
